# Generated by Django 4.1.4 on 2022-12-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_usercategory_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_query_name='post', through='news.PostCategory', to='news.category'),
        ),
    ]
