# Generated by Django 4.1.4 on 2022-12-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name_plural': 'UserCategories'},
        ),
    ]
